### PR TITLE
[Feature] support json output

### PR DESCRIPTION
**Pull request by 9to6**
Hi.
I wanna get output as json type for integrating with other application.

So I added the argument `--json` for cli.

### CODE REVIEW

**Comment by jckuester** [comment]
Hi @9to6,

thanks for your PR :+1: I guess the JSON output will useful to quite a few people.

It would be good to have some acceptance test for this, for example called `TestAcc_JsonOutput` (see other tests here: https://github.com/jckuester/awsls/blob/master/test/acc_test.go). If you don't know what to do here, I can jump in and help.

**Comment by iainelder** [comment]
@9to6 Looking forward to seeing this!

Does the JSON output include the `profile` and the `region` as extra metadata in each resource?

**Comment by 9to6** [comment]
I made test code after checking your other test. Is it ok? @jckuester

**Comment by 9to6** [comment]
@iainelder Yeah, I made PR based on original output fields.
like this...
```
[{"created_at":"N/A","id":"vpc-abcdefg","profile":"awsls","region":"ap-northeast-2","type":"aws_vpc"}]
```

**Comment by jckuester** [comment]
@9to6, I made some changes to the tests, hope this is OK for you: https://github.com/9to6/awsls/pull/1/files

Your looks good to me. Once you update this PR, we can merge it.

**Comment by 9to6** [comment]
@jckuester I merged it. Thank you for supporting me.

**Pull request merged**
